name: Check

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up
        uses: ./.github/actions/setup
      - name: Check formatting
        run: bun run format:check

  mintlify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up
        uses: ./.github/actions/setup
      - name: Check broken links
        run: bun mint broken-links --telemetry=false
      - name: Validate documentation
        run: bun mint validate --telemetry=false
